"""empty message

Revision ID: 683ab06f169a
Revises: 8ce29643765f
Create Date: 2021-03-01 16:41:01.821373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683ab06f169a'
down_revision = '8ce29643765f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
